<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\AccountRelationships;
use Form3PublicAPILib\Models\AccountUpdate;
use Form3PublicAPILib\Models\Attributes;

/**
 * Builder for model AccountUpdate
 *
 * @see AccountUpdate
 */
class AccountUpdateBuilder
{
    /**
     * @var AccountUpdate
     */
    private $instance;

    private function __construct(AccountUpdate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new account update Builder object.
     */
    public static function init(Attributes $attributes, string $id, string $organisationId, int $version): self
    {
        return new self(new AccountUpdate($attributes, $id, $organisationId, $version));
    }

    /**
     * Sets relationships field.
     */
    public function relationships(?AccountRelationships $value): self
    {
        $this->instance->setRelationships($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new account update object.
     */
    public function build(): AccountUpdate
    {
        return CoreHelper::clone($this->instance);
    }
}
