<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\AccountIdentificationData;
use Form3PublicAPILib\Models\AccountIdentificationResponse;

/**
 * Builder for model AccountIdentificationResponse
 *
 * @see AccountIdentificationResponse
 */
class AccountIdentificationResponseBuilder
{
    /**
     * @var AccountIdentificationResponse
     */
    private $instance;

    private function __construct(AccountIdentificationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new account identification response Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountIdentificationResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?AccountIdentificationData $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new account identification response object.
     */
    public function build(): AccountIdentificationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
