<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\AdviceSubmissionRelationships;
use Form3PublicAPILib\Models\RelationshipAdvices;
use Form3PublicAPILib\Models\RelationshipPayments;

/**
 * Builder for model AdviceSubmissionRelationships
 *
 * @see AdviceSubmissionRelationships
 */
class AdviceSubmissionRelationshipsBuilder
{
    /**
     * @var AdviceSubmissionRelationships
     */
    private $instance;

    private function __construct(AdviceSubmissionRelationships $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new advice submission relationships Builder object.
     */
    public static function init(): self
    {
        return new self(new AdviceSubmissionRelationships());
    }

    /**
     * Sets advice field.
     */
    public function advice(?RelationshipAdvices $value): self
    {
        $this->instance->setAdvice($value);
        return $this;
    }

    /**
     * Sets payment field.
     */
    public function payment(?RelationshipPayments $value): self
    {
        $this->instance->setPayment($value);
        return $this;
    }

    /**
     * Initializes a new advice submission relationships object.
     */
    public function build(): AdviceSubmissionRelationships
    {
        return CoreHelper::clone($this->instance);
    }
}
