<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Attributes29;

/**
 * Builder for model Attributes29
 *
 * @see Attributes29
 */
class Attributes29Builder
{
    /**
     * @var Attributes29
     */
    private $instance;

    private function __construct(Attributes29 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new attributes 29 Builder object.
     */
    public static function init(): self
    {
        return new self(new Attributes29());
    }

    /**
     * Sets admission datetime field.
     */
    public function admissionDatetime(?\DateTime $value): self
    {
        $this->instance->setAdmissionDatetime($value);
        return $this;
    }

    /**
     * Sets source gateway field.
     */
    public function sourceGateway(?string $value): self
    {
        $this->instance->setSourceGateway($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets status reason field.
     */
    public function statusReason(?string $value): self
    {
        $this->instance->setStatusReason($value);
        return $this;
    }

    /**
     * Initializes a new attributes 29 object.
     */
    public function build(): Attributes29
    {
        return CoreHelper::clone($this->instance);
    }
}
