<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Attributes4;

/**
 * Builder for model Attributes4
 *
 * @see Attributes4
 */
class Attributes4Builder
{
    /**
     * @var Attributes4
     */
    private $instance;

    private function __construct(Attributes4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new attributes 4 Builder object.
     */
    public static function init(): self
    {
        return new self(new Attributes4());
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets status reason field.
     */
    public function statusReason(?string $value): self
    {
        $this->instance->setStatusReason($value);
        return $this;
    }

    /**
     * Sets submission datetime field.
     */
    public function submissionDatetime(?\DateTime $value): self
    {
        $this->instance->setSubmissionDatetime($value);
        return $this;
    }

    /**
     * Sets transaction start datetime field.
     */
    public function transactionStartDatetime(?\DateTime $value): self
    {
        $this->instance->setTransactionStartDatetime($value);
        return $this;
    }

    /**
     * Initializes a new attributes 4 object.
     */
    public function build(): Attributes4
    {
        return CoreHelper::clone($this->instance);
    }
}
