<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Attributes19;

/**
 * Builder for model Attributes19
 *
 * @see Attributes19
 */
class Attributes19Builder
{
    /**
     * @var Attributes19
     */
    private $instance;

    private function __construct(Attributes19 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new attributes 19 Builder object.
     */
    public static function init(): self
    {
        return new self(new Attributes19());
    }

    /**
     * Sets acceptance qualifier field.
     */
    public function acceptanceQualifier(?string $value): self
    {
        $this->instance->setAcceptanceQualifier($value);
        return $this;
    }

    /**
     * Sets reference mask field.
     */
    public function referenceMask(?string $value): self
    {
        $this->instance->setReferenceMask($value);
        return $this;
    }

    /**
     * Sets user defined data field.
     */
    public function userDefinedData(?array $value): self
    {
        $this->instance->setUserDefinedData($value);
        return $this;
    }

    /**
     * Sets validation type field.
     */
    public function validationType(?string $value): self
    {
        $this->instance->setValidationType($value);
        return $this;
    }

    /**
     * Initializes a new attributes 19 object.
     */
    public function build(): Attributes19
    {
        return CoreHelper::clone($this->instance);
    }
}
