<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Attributes1;
use Form3PublicAPILib\Models\SupportedSchemes;

/**
 * Builder for model Attributes1
 *
 * @see Attributes1
 */
class Attributes1Builder
{
    /**
     * @var Attributes1
     */
    private $instance;

    private function __construct(Attributes1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new attributes 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Attributes1());
    }

    /**
     * Sets bank code field.
     */
    public function bankCode(?string $value): self
    {
        $this->instance->setBankCode($value);
        return $this;
    }

    /**
     * Sets bank name field.
     */
    public function bankName(?string $value): self
    {
        $this->instance->setBankName($value);
        return $this;
    }

    /**
     * Sets bank office title field.
     */
    public function bankOfficeTitle(?string $value): self
    {
        $this->instance->setBankOfficeTitle($value);
        return $this;
    }

    /**
     * Sets supported schemes field.
     */
    public function supportedSchemes(?SupportedSchemes $value): self
    {
        $this->instance->setSupportedSchemes($value);
        return $this;
    }

    /**
     * Initializes a new attributes 1 object.
     */
    public function build(): Attributes1
    {
        return CoreHelper::clone($this->instance);
    }
}
