<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Attributes36;

/**
 * Builder for model Attributes36
 *
 * @see Attributes36
 */
class Attributes36Builder
{
    /**
     * @var Attributes36
     */
    private $instance;

    private function __construct(Attributes36 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new attributes 36 Builder object.
     */
    public static function init(): self
    {
        return new self(new Attributes36());
    }

    /**
     * Sets scheme status code field.
     */
    public function schemeStatusCode(?string $value): self
    {
        $this->instance->setSchemeStatusCode($value);
        return $this;
    }

    /**
     * Sets scheme status code description field.
     */
    public function schemeStatusCodeDescription(?string $value): self
    {
        $this->instance->setSchemeStatusCodeDescription($value);
        return $this;
    }

    /**
     * Sets source gateway field.
     */
    public function sourceGateway(?string $value): self
    {
        $this->instance->setSourceGateway($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new attributes 36 object.
     */
    public function build(): Attributes36
    {
        return CoreHelper::clone($this->instance);
    }
}
