<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Attributes3;
use Form3PublicAPILib\Models\BeneficiaryParty;

/**
 * Builder for model Attributes3
 *
 * @see Attributes3
 */
class Attributes3Builder
{
    /**
     * @var Attributes3
     */
    private $instance;

    private function __construct(Attributes3 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new attributes 3 Builder object.
     */
    public static function init(): self
    {
        return new self(new Attributes3());
    }

    /**
     * Sets beneficiary party field.
     */
    public function beneficiaryParty(?BeneficiaryParty $value): self
    {
        $this->instance->setBeneficiaryParty($value);
        return $this;
    }

    /**
     * Sets reason code field.
     */
    public function reasonCode(?string $value): self
    {
        $this->instance->setReasonCode($value);
        return $this;
    }

    /**
     * Initializes a new attributes 3 object.
     */
    public function build(): Attributes3
    {
        return CoreHelper::clone($this->instance);
    }
}
