<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Branch;
use Form3PublicAPILib\Models\BranchCreation;

/**
 * Builder for model BranchCreation
 *
 * @see BranchCreation
 */
class BranchCreationBuilder
{
    /**
     * @var BranchCreation
     */
    private $instance;

    private function __construct(BranchCreation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new branch creation Builder object.
     */
    public static function init(Branch $data): self
    {
        return new self(new BranchCreation($data));
    }

    /**
     * Initializes a new branch creation object.
     */
    public function build(): BranchCreation
    {
        return CoreHelper::clone($this->instance);
    }
}
