<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Branch;
use Form3PublicAPILib\Models\BranchAttributes;

/**
 * Builder for model Branch
 *
 * @see Branch
 */
class BranchBuilder
{
    /**
     * @var Branch
     */
    private $instance;

    private function __construct(Branch $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new branch Builder object.
     */
    public static function init(BranchAttributes $attributes, string $id, string $organisationId): self
    {
        return new self(new Branch($attributes, $id, $organisationId));
    }

    /**
     * Sets created on field.
     */
    public function createdOn(?\DateTime $value): self
    {
        $this->instance->setCreatedOn($value);
        return $this;
    }

    /**
     * Sets modified on field.
     */
    public function modifiedOn(?\DateTime $value): self
    {
        $this->instance->setModifiedOn($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets version field.
     */
    public function version(?int $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new branch object.
     */
    public function build(): Branch
    {
        return CoreHelper::clone($this->instance);
    }
}
