<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\ChargesInformation;

/**
 * Builder for model ChargesInformation
 *
 * @see ChargesInformation
 */
class ChargesInformationBuilder
{
    /**
     * @var ChargesInformation
     */
    private $instance;

    private function __construct(ChargesInformation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new charges information Builder object.
     */
    public static function init(): self
    {
        return new self(new ChargesInformation());
    }

    /**
     * Sets bearer code field.
     */
    public function bearerCode(?string $value): self
    {
        $this->instance->setBearerCode($value);
        return $this;
    }

    /**
     * Sets receiver charges amount field.
     */
    public function receiverChargesAmount(?string $value): self
    {
        $this->instance->setReceiverChargesAmount($value);
        return $this;
    }

    /**
     * Sets receiver charges currency field.
     */
    public function receiverChargesCurrency(?string $value): self
    {
        $this->instance->setReceiverChargesCurrency($value);
        return $this;
    }

    /**
     * Sets sender charges field.
     */
    public function senderCharges(?array $value): self
    {
        $this->instance->setSenderCharges($value);
        return $this;
    }

    /**
     * Initializes a new charges information object.
     */
    public function build(): ChargesInformation
    {
        return CoreHelper::clone($this->instance);
    }
}
