<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Claim1;
use Form3PublicAPILib\Models\ClaimSubmissionRelationships;

/**
 * Builder for model ClaimSubmissionRelationships
 *
 * @see ClaimSubmissionRelationships
 */
class ClaimSubmissionRelationshipsBuilder
{
    /**
     * @var ClaimSubmissionRelationships
     */
    private $instance;

    private function __construct(ClaimSubmissionRelationships $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new claim submission relationships Builder object.
     */
    public static function init(): self
    {
        return new self(new ClaimSubmissionRelationships());
    }

    /**
     * Sets claim field.
     */
    public function claim(?Claim1 $value): self
    {
        $this->instance->setClaim($value);
        return $this;
    }

    /**
     * Initializes a new claim submission relationships object.
     */
    public function build(): ClaimSubmissionRelationships
    {
        return CoreHelper::clone($this->instance);
    }
}
