<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\ClaimReversalSubmission2;

/**
 * Builder for model ClaimReversalSubmission2
 *
 * @see ClaimReversalSubmission2
 */
class ClaimReversalSubmission2Builder
{
    /**
     * @var ClaimReversalSubmission2
     */
    private $instance;

    private function __construct(ClaimReversalSubmission2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new claim reversal submission 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new ClaimReversalSubmission2());
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new claim reversal submission 2 object.
     */
    public function build(): ClaimReversalSubmission2
    {
        return CoreHelper::clone($this->instance);
    }
}
