<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\ClaimReversal;
use Form3PublicAPILib\Models\ClaimReversalDetailsResponse;
use Form3PublicAPILib\Models\Links;

/**
 * Builder for model ClaimReversalDetailsResponse
 *
 * @see ClaimReversalDetailsResponse
 */
class ClaimReversalDetailsResponseBuilder
{
    /**
     * @var ClaimReversalDetailsResponse
     */
    private $instance;

    private function __construct(ClaimReversalDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new claim reversal details response Builder object.
     */
    public static function init(): self
    {
        return new self(new ClaimReversalDetailsResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?ClaimReversal $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new claim reversal details response object.
     */
    public function build(): ClaimReversalDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
