<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\ClaimSubmission;
use Form3PublicAPILib\Models\ClaimSubmissionDetailsResponse;
use Form3PublicAPILib\Models\Links;

/**
 * Builder for model ClaimSubmissionDetailsResponse
 *
 * @see ClaimSubmissionDetailsResponse
 */
class ClaimSubmissionDetailsResponseBuilder
{
    /**
     * @var ClaimSubmissionDetailsResponse
     */
    private $instance;

    private function __construct(ClaimSubmissionDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new claim submission details response Builder object.
     */
    public static function init(): self
    {
        return new self(new ClaimSubmissionDetailsResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?ClaimSubmission $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new claim submission details response object.
     */
    public function build(): ClaimSubmissionDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
