<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\ClaimReversal;
use Form3PublicAPILib\Models\ClaimReversalCreation;

/**
 * Builder for model ClaimReversalCreation
 *
 * @see ClaimReversalCreation
 */
class ClaimReversalCreationBuilder
{
    /**
     * @var ClaimReversalCreation
     */
    private $instance;

    private function __construct(ClaimReversalCreation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new claim reversal creation Builder object.
     */
    public static function init(ClaimReversal $data): self
    {
        return new self(new ClaimReversalCreation($data));
    }

    /**
     * Initializes a new claim reversal creation object.
     */
    public function build(): ClaimReversalCreation
    {
        return CoreHelper::clone($this->instance);
    }
}
