<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Attributes49;
use Form3PublicAPILib\Models\Data;

/**
 * Builder for model Data
 *
 * @see Data
 */
class DataBuilder
{
    /**
     * @var Data
     */
    private $instance;

    private function __construct(Data $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data Builder object.
     */
    public static function init(): self
    {
        return new self(new Data());
    }

    /**
     * Sets attributes field.
     */
    public function attributes(?Attributes49 $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Sets created on field.
     */
    public function createdOn(?\DateTime $value): self
    {
        $this->instance->setCreatedOn($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets modified on field.
     */
    public function modifiedOn(?\DateTime $value): self
    {
        $this->instance->setModifiedOn($value);
        return $this;
    }

    /**
     * Sets organisation id field.
     */
    public function organisationId(?string $value): self
    {
        $this->instance->setOrganisationId($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets version field.
     */
    public function version(?int $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new data object.
     */
    public function build(): Data
    {
        return CoreHelper::clone($this->instance);
    }
}
