<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DebtorParty1;

/**
 * Builder for model DebtorParty1
 *
 * @see DebtorParty1
 */
class DebtorParty1Builder
{
    /**
     * @var DebtorParty1
     */
    private $instance;

    private function __construct(DebtorParty1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new debtor party 1 Builder object.
     */
    public static function init(string $accountName, string $accountNumber, string $bankId): self
    {
        return new self(new DebtorParty1($accountName, $accountNumber, $bankId));
    }

    /**
     * Initializes a new debtor party 1 object.
     */
    public function build(): DebtorParty1
    {
        return CoreHelper::clone($this->instance);
    }
}
