<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DirectDebitReversalSubmission;
use Form3PublicAPILib\Models\DirectDebitReversalSubmissionCreation;

/**
 * Builder for model DirectDebitReversalSubmissionCreation
 *
 * @see DirectDebitReversalSubmissionCreation
 */
class DirectDebitReversalSubmissionCreationBuilder
{
    /**
     * @var DirectDebitReversalSubmissionCreation
     */
    private $instance;

    private function __construct(DirectDebitReversalSubmissionCreation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new direct debit reversal submission creation Builder object.
     */
    public static function init(): self
    {
        return new self(new DirectDebitReversalSubmissionCreation());
    }

    /**
     * Sets data field.
     */
    public function data(?DirectDebitReversalSubmission $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new direct debit reversal submission creation object.
     */
    public function build(): DirectDebitReversalSubmissionCreation
    {
        return CoreHelper::clone($this->instance);
    }
}
