<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DirectDebitReturn;
use Form3PublicAPILib\Models\DirectDebitReturnCreation;

/**
 * Builder for model DirectDebitReturnCreation
 *
 * @see DirectDebitReturnCreation
 */
class DirectDebitReturnCreationBuilder
{
    /**
     * @var DirectDebitReturnCreation
     */
    private $instance;

    private function __construct(DirectDebitReturnCreation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new direct debit return creation Builder object.
     */
    public static function init(): self
    {
        return new self(new DirectDebitReturnCreation());
    }

    /**
     * Sets data field.
     */
    public function data(?DirectDebitReturn $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new direct debit return creation object.
     */
    public function build(): DirectDebitReturnCreation
    {
        return CoreHelper::clone($this->instance);
    }
}
