<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DirectDebitRecallAdmission;
use Form3PublicAPILib\Models\DirectDebitRecallAdmissionDetailsResponse;
use Form3PublicAPILib\Models\Links;

/**
 * Builder for model DirectDebitRecallAdmissionDetailsResponse
 *
 * @see DirectDebitRecallAdmissionDetailsResponse
 */
class DirectDebitRecallAdmissionDetailsResponseBuilder
{
    /**
     * @var DirectDebitRecallAdmissionDetailsResponse
     */
    private $instance;

    private function __construct(DirectDebitRecallAdmissionDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new direct debit recall admission details response Builder object.
     */
    public static function init(): self
    {
        return new self(new DirectDebitRecallAdmissionDetailsResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?DirectDebitRecallAdmission $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new direct debit recall admission details response object.
     */
    public function build(): DirectDebitRecallAdmissionDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
