<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DirectDebitReturn2;

/**
 * Builder for model DirectDebitReturn2
 *
 * @see DirectDebitReturn2
 */
class DirectDebitReturn2Builder
{
    /**
     * @var DirectDebitReturn2
     */
    private $instance;

    private function __construct(DirectDebitReturn2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new direct debit return 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new DirectDebitReturn2());
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new direct debit return 2 object.
     */
    public function build(): DirectDebitReturn2
    {
        return CoreHelper::clone($this->instance);
    }
}
