<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DirectDebitRecall;
use Form3PublicAPILib\Models\DirectDebitRecallCreation;

/**
 * Builder for model DirectDebitRecallCreation
 *
 * @see DirectDebitRecallCreation
 */
class DirectDebitRecallCreationBuilder
{
    /**
     * @var DirectDebitRecallCreation
     */
    private $instance;

    private function __construct(DirectDebitRecallCreation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new direct debit recall creation Builder object.
     */
    public static function init(): self
    {
        return new self(new DirectDebitRecallCreation());
    }

    /**
     * Sets data field.
     */
    public function data(?DirectDebitRecall $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new direct debit recall creation object.
     */
    public function build(): DirectDebitRecallCreation
    {
        return CoreHelper::clone($this->instance);
    }
}
