<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DirectDebitReturn;
use Form3PublicAPILib\Models\DirectDebitReturnCreationResponse;
use Form3PublicAPILib\Models\Links;

/**
 * Builder for model DirectDebitReturnCreationResponse
 *
 * @see DirectDebitReturnCreationResponse
 */
class DirectDebitReturnCreationResponseBuilder
{
    /**
     * @var DirectDebitReturnCreationResponse
     */
    private $instance;

    private function __construct(DirectDebitReturnCreationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new direct debit return creation response Builder object.
     */
    public static function init(): self
    {
        return new self(new DirectDebitReturnCreationResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?DirectDebitReturn $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new direct debit return creation response object.
     */
    public function build(): DirectDebitReturnCreationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
