<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DirectDebitSubmission;
use Form3PublicAPILib\Models\DirectDebitSubmissionCreationResponse;
use Form3PublicAPILib\Models\Links;

/**
 * Builder for model DirectDebitSubmissionCreationResponse
 *
 * @see DirectDebitSubmissionCreationResponse
 */
class DirectDebitSubmissionCreationResponseBuilder
{
    /**
     * @var DirectDebitSubmissionCreationResponse
     */
    private $instance;

    private function __construct(DirectDebitSubmissionCreationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new direct debit submission creation response Builder object.
     */
    public static function init(): self
    {
        return new self(new DirectDebitSubmissionCreationResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?DirectDebitSubmission $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new direct debit submission creation response object.
     */
    public function build(): DirectDebitSubmissionCreationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
