<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DirectDebitReversal;
use Form3PublicAPILib\Models\DirectDebitReversalCreationResponse;
use Form3PublicAPILib\Models\Links;

/**
 * Builder for model DirectDebitReversalCreationResponse
 *
 * @see DirectDebitReversalCreationResponse
 */
class DirectDebitReversalCreationResponseBuilder
{
    /**
     * @var DirectDebitReversalCreationResponse
     */
    private $instance;

    private function __construct(DirectDebitReversalCreationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new direct debit reversal creation response Builder object.
     */
    public static function init(): self
    {
        return new self(new DirectDebitReversalCreationResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?DirectDebitReversal $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new direct debit reversal creation response object.
     */
    public function build(): DirectDebitReversalCreationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
