<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DirectDebitDecisionAdmission;
use Form3PublicAPILib\Models\DirectDebitDecisionAdmissionDetailsResponse;
use Form3PublicAPILib\Models\Links;

/**
 * Builder for model DirectDebitDecisionAdmissionDetailsResponse
 *
 * @see DirectDebitDecisionAdmissionDetailsResponse
 */
class DirectDebitDecisionAdmissionDetailsResponseBuilder
{
    /**
     * @var DirectDebitDecisionAdmissionDetailsResponse
     */
    private $instance;

    private function __construct(DirectDebitDecisionAdmissionDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new direct debit decision admission details response Builder object.
     */
    public static function init(): self
    {
        return new self(new DirectDebitDecisionAdmissionDetailsResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?DirectDebitDecisionAdmission $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new direct debit decision admission details response object.
     */
    public function build(): DirectDebitDecisionAdmissionDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
