<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DirectDebit;
use Form3PublicAPILib\Models\DirectDebitReturn;
use Form3PublicAPILib\Models\DirectDebitWithReturn;

/**
 * Builder for model DirectDebitWithReturn
 *
 * @see DirectDebitWithReturn
 */
class DirectDebitWithReturnBuilder
{
    /**
     * @var DirectDebitWithReturn
     */
    private $instance;

    private function __construct(DirectDebitWithReturn $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new direct debit with return Builder object.
     */
    public static function init(): self
    {
        return new self(new DirectDebitWithReturn());
    }

    /**
     * Sets direct debit field.
     */
    public function directDebit(?DirectDebit $value): self
    {
        $this->instance->setDirectDebit($value);
        return $this;
    }

    /**
     * Sets direct debit return field.
     */
    public function directDebitReturn(?DirectDebitReturn $value): self
    {
        $this->instance->setDirectDebitReturn($value);
        return $this;
    }

    /**
     * Initializes a new direct debit with return object.
     */
    public function build(): DirectDebitWithReturn
    {
        return CoreHelper::clone($this->instance);
    }
}
