<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\DuplicateTransactionInformation;

/**
 * Builder for model DuplicateTransactionInformation
 *
 * @see DuplicateTransactionInformation
 */
class DuplicateTransactionInformationBuilder
{
    /**
     * @var DuplicateTransactionInformation
     */
    private $instance;

    private function __construct(DuplicateTransactionInformation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new duplicate transaction information Builder object.
     */
    public static function init(): self
    {
        return new self(new DuplicateTransactionInformation());
    }

    /**
     * Sets end to end reference field.
     */
    public function endToEndReference(?string $value): self
    {
        $this->instance->setEndToEndReference($value);
        return $this;
    }

    /**
     * Sets references field.
     */
    public function references(?array $value): self
    {
        $this->instance->setReferences($value);
        return $this;
    }

    /**
     * Sets scheme transaction id field.
     */
    public function schemeTransactionId(?string $value): self
    {
        $this->instance->setSchemeTransactionId($value);
        return $this;
    }

    /**
     * Initializes a new duplicate transaction information object.
     */
    public function build(): DuplicateTransactionInformation
    {
        return CoreHelper::clone($this->instance);
    }
}
