<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Fx;

/**
 * Builder for model Fx
 *
 * @see Fx
 */
class FxBuilder
{
    /**
     * @var Fx
     */
    private $instance;

    private function __construct(Fx $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new fx Builder object.
     */
    public static function init(): self
    {
        return new self(new Fx());
    }

    /**
     * Sets contract reference field.
     */
    public function contractReference(?string $value): self
    {
        $this->instance->setContractReference($value);
        return $this;
    }

    /**
     * Sets exchange rate field.
     */
    public function exchangeRate(?string $value): self
    {
        $this->instance->setExchangeRate($value);
        return $this;
    }

    /**
     * Sets original amount field.
     */
    public function originalAmount(?string $value): self
    {
        $this->instance->setOriginalAmount($value);
        return $this;
    }

    /**
     * Sets original currency field.
     */
    public function originalCurrency(?string $value): self
    {
        $this->instance->setOriginalCurrency($value);
        return $this;
    }

    /**
     * Initializes a new fx object.
     */
    public function build(): Fx
    {
        return CoreHelper::clone($this->instance);
    }
}
