<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\FxDeal;

/**
 * Builder for model FxDeal
 *
 * @see FxDeal
 */
class FxDealBuilder
{
    /**
     * @var FxDeal
     */
    private $instance;

    private function __construct(FxDeal $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new fx deal Builder object.
     */
    public static function init(): self
    {
        return new self(new FxDeal());
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new fx deal object.
     */
    public function build(): FxDeal
    {
        return CoreHelper::clone($this->instance);
    }
}
