<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\ListTransactionFilesResponse;

/**
 * Builder for model ListTransactionFilesResponse
 *
 * @see ListTransactionFilesResponse
 */
class ListTransactionFilesResponseBuilder
{
    /**
     * @var ListTransactionFilesResponse
     */
    private $instance;

    private function __construct(ListTransactionFilesResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new list transaction files response Builder object.
     */
    public static function init(array $data): self
    {
        return new self(new ListTransactionFilesResponse($data));
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new list transaction files response object.
     */
    public function build(): ListTransactionFilesResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
