<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\ListSchemeFilesResponse;

/**
 * Builder for model ListSchemeFilesResponse
 *
 * @see ListSchemeFilesResponse
 */
class ListSchemeFilesResponseBuilder
{
    /**
     * @var ListSchemeFilesResponse
     */
    private $instance;

    private function __construct(ListSchemeFilesResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new list scheme files response Builder object.
     */
    public static function init(array $data): self
    {
        return new self(new ListSchemeFilesResponse($data));
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new list scheme files response object.
     */
    public function build(): ListSchemeFilesResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
