<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\MandateReturn;
use Form3PublicAPILib\Models\MandateReturnCreationResponse;

/**
 * Builder for model MandateReturnCreationResponse
 *
 * @see MandateReturnCreationResponse
 */
class MandateReturnCreationResponseBuilder
{
    /**
     * @var MandateReturnCreationResponse
     */
    private $instance;

    private function __construct(MandateReturnCreationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new mandate return creation response Builder object.
     */
    public static function init(): self
    {
        return new self(new MandateReturnCreationResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?MandateReturn $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new mandate return creation response object.
     */
    public function build(): MandateReturnCreationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
