<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\MandateAdmission2;
use Form3PublicAPILib\Models\MandateRelationships;
use Form3PublicAPILib\Models\MandateReturn2;
use Form3PublicAPILib\Models\MandateSubmission2;
use Form3PublicAPILib\Models\MostRecentCollection2;

/**
 * Builder for model MandateRelationships
 *
 * @see MandateRelationships
 */
class MandateRelationshipsBuilder
{
    /**
     * @var MandateRelationships
     */
    private $instance;

    private function __construct(MandateRelationships $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new mandate relationships Builder object.
     */
    public static function init(): self
    {
        return new self(new MandateRelationships());
    }

    /**
     * Sets mandate admission field.
     */
    public function mandateAdmission(?MandateAdmission2 $value): self
    {
        $this->instance->setMandateAdmission($value);
        return $this;
    }

    /**
     * Sets mandate return field.
     */
    public function mandateReturn(?MandateReturn2 $value): self
    {
        $this->instance->setMandateReturn($value);
        return $this;
    }

    /**
     * Sets mandate submission field.
     */
    public function mandateSubmission(?MandateSubmission2 $value): self
    {
        $this->instance->setMandateSubmission($value);
        return $this;
    }

    /**
     * Sets most recent collection field.
     */
    public function mostRecentCollection(?MostRecentCollection2 $value): self
    {
        $this->instance->setMostRecentCollection($value);
        return $this;
    }

    /**
     * Initializes a new mandate relationships object.
     */
    public function build(): MandateRelationships
    {
        return CoreHelper::clone($this->instance);
    }
}
