<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Mandate2;
use Form3PublicAPILib\Models\MandateAdmissionRelationships;

/**
 * Builder for model MandateAdmissionRelationships
 *
 * @see MandateAdmissionRelationships
 */
class MandateAdmissionRelationshipsBuilder
{
    /**
     * @var MandateAdmissionRelationships
     */
    private $instance;

    private function __construct(MandateAdmissionRelationships $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new mandate admission relationships Builder object.
     */
    public static function init(): self
    {
        return new self(new MandateAdmissionRelationships());
    }

    /**
     * Sets mandate field.
     */
    public function mandate(?Mandate2 $value): self
    {
        $this->instance->setMandate($value);
        return $this;
    }

    /**
     * Initializes a new mandate admission relationships object.
     */
    public function build(): MandateAdmissionRelationships
    {
        return CoreHelper::clone($this->instance);
    }
}
