<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\MandateReturnSubmission;
use Form3PublicAPILib\Models\MandateReturnSubmissionCreationResponse;

/**
 * Builder for model MandateReturnSubmissionCreationResponse
 *
 * @see MandateReturnSubmissionCreationResponse
 */
class MandateReturnSubmissionCreationResponseBuilder
{
    /**
     * @var MandateReturnSubmissionCreationResponse
     */
    private $instance;

    private function __construct(MandateReturnSubmissionCreationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new mandate return submission creation response Builder object.
     */
    public static function init(): self
    {
        return new self(new MandateReturnSubmissionCreationResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?MandateReturnSubmission $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new mandate return submission creation response object.
     */
    public function build(): MandateReturnSubmissionCreationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
