<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\MandateReturn;
use Form3PublicAPILib\Models\MandateReturnDetailsResponse;

/**
 * Builder for model MandateReturnDetailsResponse
 *
 * @see MandateReturnDetailsResponse
 */
class MandateReturnDetailsResponseBuilder
{
    /**
     * @var MandateReturnDetailsResponse
     */
    private $instance;

    private function __construct(MandateReturnDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new mandate return details response Builder object.
     */
    public static function init(): self
    {
        return new self(new MandateReturnDetailsResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?MandateReturn $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new mandate return details response object.
     */
    public function build(): MandateReturnDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
