<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\MandateAdmission;
use Form3PublicAPILib\Models\MandateAdmissionDetailsResponse;

/**
 * Builder for model MandateAdmissionDetailsResponse
 *
 * @see MandateAdmissionDetailsResponse
 */
class MandateAdmissionDetailsResponseBuilder
{
    /**
     * @var MandateAdmissionDetailsResponse
     */
    private $instance;

    private function __construct(MandateAdmissionDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new mandate admission details response Builder object.
     */
    public static function init(): self
    {
        return new self(new MandateAdmissionDetailsResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?MandateAdmission $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new mandate admission details response object.
     */
    public function build(): MandateAdmissionDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
