<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Attributes46;
use Form3PublicAPILib\Models\MandateReturn;
use Form3PublicAPILib\Models\Relationships17;

/**
 * Builder for model MandateReturn
 *
 * @see MandateReturn
 */
class MandateReturnBuilder
{
    /**
     * @var MandateReturn
     */
    private $instance;

    private function __construct(MandateReturn $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new mandate return Builder object.
     */
    public static function init(): self
    {
        return new self(new MandateReturn());
    }

    /**
     * Sets attributes field.
     */
    public function attributes(?Attributes46 $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Sets created on field.
     */
    public function createdOn(?\DateTime $value): self
    {
        $this->instance->setCreatedOn($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets modified on field.
     */
    public function modifiedOn(?\DateTime $value): self
    {
        $this->instance->setModifiedOn($value);
        return $this;
    }

    /**
     * Sets organisation id field.
     */
    public function organisationId(?string $value): self
    {
        $this->instance->setOrganisationId($value);
        return $this;
    }

    /**
     * Sets relationships field.
     */
    public function relationships(?Relationships17 $value): self
    {
        $this->instance->setRelationships($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets version field.
     */
    public function version(?int $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new mandate return object.
     */
    public function build(): MandateReturn
    {
        return CoreHelper::clone($this->instance);
    }
}
