<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\NewQuery;
use Form3PublicAPILib\Models\NewQueryRelationships;
use Form3PublicAPILib\Models\QueryAttributes;

/**
 * Builder for model NewQuery
 *
 * @see NewQuery
 */
class NewQueryBuilder
{
    /**
     * @var NewQuery
     */
    private $instance;

    private function __construct(NewQuery $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new new query Builder object.
     */
    public static function init(QueryAttributes $attributes, string $id, string $organisationId): self
    {
        return new self(new NewQuery($attributes, $id, $organisationId));
    }

    /**
     * Sets relationships field.
     */
    public function relationships(?NewQueryRelationships $value): self
    {
        $this->instance->setRelationships($value);
        return $this;
    }

    /**
     * Initializes a new new query object.
     */
    public function build(): NewQuery
    {
        return CoreHelper::clone($this->instance);
    }
}
