<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Attributes51;
use Form3PublicAPILib\Models\NewRecall;
use Form3PublicAPILib\Models\RecallRelationships;

/**
 * Builder for model NewRecall
 *
 * @see NewRecall
 */
class NewRecallBuilder
{
    /**
     * @var NewRecall
     */
    private $instance;

    private function __construct(NewRecall $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new new recall Builder object.
     */
    public static function init(string $id, string $organisationId): self
    {
        return new self(new NewRecall($id, $organisationId));
    }

    /**
     * Sets attributes field.
     */
    public function attributes(?Attributes51 $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Sets relationships field.
     */
    public function relationships(?RecallRelationships $value): self
    {
        $this->instance->setRelationships($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets version field.
     */
    public function version(?int $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new new recall object.
     */
    public function build(): NewRecall
    {
        return CoreHelper::clone($this->instance);
    }
}
