<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\OrganisationDetailsListResponse;

/**
 * Builder for model OrganisationDetailsListResponse
 *
 * @see OrganisationDetailsListResponse
 */
class OrganisationDetailsListResponseBuilder
{
    /**
     * @var OrganisationDetailsListResponse
     */
    private $instance;

    private function __construct(OrganisationDetailsListResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new organisation details list response Builder object.
     */
    public static function init(array $data): self
    {
        return new self(new OrganisationDetailsListResponse($data));
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new organisation details list response object.
     */
    public function build(): OrganisationDetailsListResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
