<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\PaymentSubmission2;

/**
 * Builder for model PaymentSubmission2
 *
 * @see PaymentSubmission2
 */
class PaymentSubmission2Builder
{
    /**
     * @var PaymentSubmission2
     */
    private $instance;

    private function __construct(PaymentSubmission2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new payment submission 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new PaymentSubmission2());
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new payment submission 2 object.
     */
    public function build(): PaymentSubmission2
    {
        return CoreHelper::clone($this->instance);
    }
}
