<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\PaymentTypeInformation;

/**
 * Builder for model PaymentTypeInformation
 *
 * @see PaymentTypeInformation
 */
class PaymentTypeInformationBuilder
{
    /**
     * @var PaymentTypeInformation
     */
    private $instance;

    private function __construct(PaymentTypeInformation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new payment type information Builder object.
     */
    public static function init(): self
    {
        return new self(new PaymentTypeInformation());
    }

    /**
     * Sets amount field.
     */
    public function amount(?string $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets category purpose field.
     */
    public function categoryPurpose(?string $value): self
    {
        $this->instance->setCategoryPurpose($value);
        return $this;
    }

    /**
     * Sets currency field.
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets payment purpose field.
     */
    public function paymentPurpose(?string $value): self
    {
        $this->instance->setPaymentPurpose($value);
        return $this;
    }

    /**
     * Sets processing date field.
     */
    public function processingDate(?\DateTime $value): self
    {
        $this->instance->setProcessingDate($value);
        return $this;
    }

    /**
     * Sets remittance information field.
     */
    public function remittanceInformation(?string $value): self
    {
        $this->instance->setRemittanceInformation($value);
        return $this;
    }

    /**
     * Sets scheme payment sub type field.
     */
    public function schemePaymentSubType(?string $value): self
    {
        $this->instance->setSchemePaymentSubType($value);
        return $this;
    }

    /**
     * Sets scheme payment type field.
     */
    public function schemePaymentType(?string $value): self
    {
        $this->instance->setSchemePaymentType($value);
        return $this;
    }

    /**
     * Initializes a new payment type information object.
     */
    public function build(): PaymentTypeInformation
    {
        return CoreHelper::clone($this->instance);
    }
}
