<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\NewQueryResponseSubmission;
use Form3PublicAPILib\Models\QueryResponseSubmissionCreation;

/**
 * Builder for model QueryResponseSubmissionCreation
 *
 * @see QueryResponseSubmissionCreation
 */
class QueryResponseSubmissionCreationBuilder
{
    /**
     * @var QueryResponseSubmissionCreation
     */
    private $instance;

    private function __construct(QueryResponseSubmissionCreation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new query response submission creation Builder object.
     */
    public static function init(NewQueryResponseSubmission $data): self
    {
        return new self(new QueryResponseSubmissionCreation($data));
    }

    /**
     * Initializes a new query response submission creation object.
     */
    public function build(): QueryResponseSubmissionCreation
    {
        return CoreHelper::clone($this->instance);
    }
}
