<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\QueryResponse;
use Form3PublicAPILib\Models\QueryResponseResponse;

/**
 * Builder for model QueryResponseResponse
 *
 * @see QueryResponseResponse
 */
class QueryResponseResponseBuilder
{
    /**
     * @var QueryResponseResponse
     */
    private $instance;

    private function __construct(QueryResponseResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new query response response Builder object.
     */
    public static function init(QueryResponse $data): self
    {
        return new self(new QueryResponseResponse($data));
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new query response response object.
     */
    public function build(): QueryResponseResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
