<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\QueryResponseRelationships;
use Form3PublicAPILib\Models\RelationshipQueryResponseAdmission;
use Form3PublicAPILib\Models\RelationshipQueryResponseSubmission;
use Form3PublicAPILib\Models\RelationshipsFullQuery;

/**
 * Builder for model QueryResponseRelationships
 *
 * @see QueryResponseRelationships
 */
class QueryResponseRelationshipsBuilder
{
    /**
     * @var QueryResponseRelationships
     */
    private $instance;

    private function __construct(QueryResponseRelationships $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new query response relationships Builder object.
     */
    public static function init(): self
    {
        return new self(new QueryResponseRelationships());
    }

    /**
     * Sets query field.
     */
    public function query(?RelationshipsFullQuery $value): self
    {
        $this->instance->setQuery($value);
        return $this;
    }

    /**
     * Sets query response admission field.
     */
    public function queryResponseAdmission(?RelationshipQueryResponseAdmission $value): self
    {
        $this->instance->setQueryResponseAdmission($value);
        return $this;
    }

    /**
     * Sets query response submission field.
     */
    public function queryResponseSubmission(?RelationshipQueryResponseSubmission $value): self
    {
        $this->instance->setQueryResponseSubmission($value);
        return $this;
    }

    /**
     * Initializes a new query response relationships object.
     */
    public function build(): QueryResponseRelationships
    {
        return CoreHelper::clone($this->instance);
    }
}
