<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\QuerySubmission;
use Form3PublicAPILib\Models\QuerySubmissionResponse;

/**
 * Builder for model QuerySubmissionResponse
 *
 * @see QuerySubmissionResponse
 */
class QuerySubmissionResponseBuilder
{
    /**
     * @var QuerySubmissionResponse
     */
    private $instance;

    private function __construct(QuerySubmissionResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new query submission response Builder object.
     */
    public static function init(QuerySubmission $data): self
    {
        return new self(new QuerySubmissionResponse($data));
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new query submission response object.
     */
    public function build(): QuerySubmissionResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
