<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\QueryResponseAdmissionAttributes;

/**
 * Builder for model QueryResponseAdmissionAttributes
 *
 * @see QueryResponseAdmissionAttributes
 */
class QueryResponseAdmissionAttributesBuilder
{
    /**
     * @var QueryResponseAdmissionAttributes
     */
    private $instance;

    private function __construct(QueryResponseAdmissionAttributes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new query response admission attributes Builder object.
     */
    public static function init(string $status): self
    {
        return new self(new QueryResponseAdmissionAttributes($status));
    }

    /**
     * Sets status reason field.
     */
    public function statusReason(?string $value): self
    {
        $this->instance->setStatusReason($value);
        return $this;
    }

    /**
     * Initializes a new query response admission attributes object.
     */
    public function build(): QueryResponseAdmissionAttributes
    {
        return CoreHelper::clone($this->instance);
    }
}
