<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\QueryResponseSubmissionRelationships;
use Form3PublicAPILib\Models\RelationshipsFullQuery;
use Form3PublicAPILib\Models\RelationshipsFullQueryResponse;

/**
 * Builder for model QueryResponseSubmissionRelationships
 *
 * @see QueryResponseSubmissionRelationships
 */
class QueryResponseSubmissionRelationshipsBuilder
{
    /**
     * @var QueryResponseSubmissionRelationships
     */
    private $instance;

    private function __construct(QueryResponseSubmissionRelationships $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new query response submission relationships Builder object.
     */
    public static function init(): self
    {
        return new self(new QueryResponseSubmissionRelationships());
    }

    /**
     * Sets query field.
     */
    public function query(?RelationshipsFullQuery $value): self
    {
        $this->instance->setQuery($value);
        return $this;
    }

    /**
     * Sets query response field.
     */
    public function queryResponse(?RelationshipsFullQueryResponse $value): self
    {
        $this->instance->setQueryResponse($value);
        return $this;
    }

    /**
     * Initializes a new query response submission relationships object.
     */
    public function build(): QueryResponseSubmissionRelationships
    {
        return CoreHelper::clone($this->instance);
    }
}
