<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\RecallReversalAdmission;
use Form3PublicAPILib\Models\RecallReversalAdmissionAttributes;
use Form3PublicAPILib\Models\Relationships22;

/**
 * Builder for model RecallReversalAdmission
 *
 * @see RecallReversalAdmission
 */
class RecallReversalAdmissionBuilder
{
    /**
     * @var RecallReversalAdmission
     */
    private $instance;

    private function __construct(RecallReversalAdmission $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new recall reversal admission Builder object.
     */
    public static function init(string $id, string $organisationId): self
    {
        return new self(new RecallReversalAdmission($id, $organisationId));
    }

    /**
     * Sets attributes field.
     */
    public function attributes(?RecallReversalAdmissionAttributes $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Sets created on field.
     */
    public function createdOn(?\DateTime $value): self
    {
        $this->instance->setCreatedOn($value);
        return $this;
    }

    /**
     * Sets modified on field.
     */
    public function modifiedOn(?\DateTime $value): self
    {
        $this->instance->setModifiedOn($value);
        return $this;
    }

    /**
     * Sets relationships field.
     */
    public function relationships(?Relationships22 $value): self
    {
        $this->instance->setRelationships($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets version field.
     */
    public function version(?int $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new recall reversal admission object.
     */
    public function build(): RecallReversalAdmission
    {
        return CoreHelper::clone($this->instance);
    }
}
