<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\RecallDecisionSubmissionAttributes;

/**
 * Builder for model RecallDecisionSubmissionAttributes
 *
 * @see RecallDecisionSubmissionAttributes
 */
class RecallDecisionSubmissionAttributesBuilder
{
    /**
     * @var RecallDecisionSubmissionAttributes
     */
    private $instance;

    private function __construct(RecallDecisionSubmissionAttributes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new recall decision submission attributes Builder object.
     */
    public static function init(): self
    {
        return new self(new RecallDecisionSubmissionAttributes());
    }

    /**
     * Sets auto field.
     */
    public function auto(?bool $value): self
    {
        $this->instance->setAuto($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets status reason field.
     */
    public function statusReason(?string $value): self
    {
        $this->instance->setStatusReason($value);
        return $this;
    }

    /**
     * Sets submission datetime field.
     */
    public function submissionDatetime(?\DateTime $value): self
    {
        $this->instance->setSubmissionDatetime($value);
        return $this;
    }

    /**
     * Initializes a new recall decision submission attributes object.
     */
    public function build(): RecallDecisionSubmissionAttributes
    {
        return CoreHelper::clone($this->instance);
    }
}
