<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\RecallReversalAdmissionAttributes;

/**
 * Builder for model RecallReversalAdmissionAttributes
 *
 * @see RecallReversalAdmissionAttributes
 */
class RecallReversalAdmissionAttributesBuilder
{
    /**
     * @var RecallReversalAdmissionAttributes
     */
    private $instance;

    private function __construct(RecallReversalAdmissionAttributes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new recall reversal admission attributes Builder object.
     */
    public static function init(): self
    {
        return new self(new RecallReversalAdmissionAttributes());
    }

    /**
     * Sets scheme status code field.
     */
    public function schemeStatusCode(?string $value): self
    {
        $this->instance->setSchemeStatusCode($value);
        return $this;
    }

    /**
     * Sets source gateway field.
     */
    public function sourceGateway(?string $value): self
    {
        $this->instance->setSourceGateway($value);
        return $this;
    }

    /**
     * Initializes a new recall reversal admission attributes object.
     */
    public function build(): RecallReversalAdmissionAttributes
    {
        return CoreHelper::clone($this->instance);
    }
}
