<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\RecallRelationships;
use Form3PublicAPILib\Models\RelationshipLinks;

/**
 * Builder for model RecallRelationships
 *
 * @see RecallRelationships
 */
class RecallRelationshipsBuilder
{
    /**
     * @var RecallRelationships
     */
    private $instance;

    private function __construct(RecallRelationships $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new recall relationships Builder object.
     */
    public static function init(): self
    {
        return new self(new RecallRelationships());
    }

    /**
     * Sets payment field.
     */
    public function payment(?RelationshipLinks $value): self
    {
        $this->instance->setPayment($value);
        return $this;
    }

    /**
     * Sets recall admission field.
     */
    public function recallAdmission(?RelationshipLinks $value): self
    {
        $this->instance->setRecallAdmission($value);
        return $this;
    }

    /**
     * Sets recall decisions field.
     */
    public function recallDecisions(?RelationshipLinks $value): self
    {
        $this->instance->setRecallDecisions($value);
        return $this;
    }

    /**
     * Sets recall reversal field.
     */
    public function recallReversal(?RelationshipLinks $value): self
    {
        $this->instance->setRecallReversal($value);
        return $this;
    }

    /**
     * Sets recall submission field.
     */
    public function recallSubmission(?RelationshipLinks $value): self
    {
        $this->instance->setRecallSubmission($value);
        return $this;
    }

    /**
     * Initializes a new recall relationships object.
     */
    public function build(): RecallRelationships
    {
        return CoreHelper::clone($this->instance);
    }
}
