<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\RelationshipsPaymentAdmission;

/**
 * Builder for model RelationshipsPaymentAdmission
 *
 * @see RelationshipsPaymentAdmission
 */
class RelationshipsPaymentAdmissionBuilder
{
    /**
     * @var RelationshipsPaymentAdmission
     */
    private $instance;

    private function __construct(RelationshipsPaymentAdmission $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new relationships payment admission Builder object.
     */
    public static function init(): self
    {
        return new self(new RelationshipsPaymentAdmission());
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new relationships payment admission object.
     */
    public function build(): RelationshipsPaymentAdmission
    {
        return CoreHelper::clone($this->instance);
    }
}
