<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Mandate2;
use Form3PublicAPILib\Models\MandateReturnSubmission2;
use Form3PublicAPILib\Models\Relationships17;

/**
 * Builder for model Relationships17
 *
 * @see Relationships17
 */
class Relationships17Builder
{
    /**
     * @var Relationships17
     */
    private $instance;

    private function __construct(Relationships17 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new relationships 17 Builder object.
     */
    public static function init(): self
    {
        return new self(new Relationships17());
    }

    /**
     * Sets mandate field.
     */
    public function mandate(?Mandate2 $value): self
    {
        $this->instance->setMandate($value);
        return $this;
    }

    /**
     * Sets mandate return submission field.
     */
    public function mandateReturnSubmission(?MandateReturnSubmission2 $value): self
    {
        $this->instance->setMandateReturnSubmission($value);
        return $this;
    }

    /**
     * Initializes a new relationships 17 object.
     */
    public function build(): Relationships17
    {
        return CoreHelper::clone($this->instance);
    }
}
