<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\RelationshipLinks;
use Form3PublicAPILib\Models\Relationships21;

/**
 * Builder for model Relationships21
 *
 * @see Relationships21
 */
class Relationships21Builder
{
    /**
     * @var Relationships21
     */
    private $instance;

    private function __construct(Relationships21 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new relationships 21 Builder object.
     */
    public static function init(): self
    {
        return new self(new Relationships21());
    }

    /**
     * Sets payment field.
     */
    public function payment(?RelationshipLinks $value): self
    {
        $this->instance->setPayment($value);
        return $this;
    }

    /**
     * Sets recall field.
     */
    public function recall(?RelationshipLinks $value): self
    {
        $this->instance->setRecall($value);
        return $this;
    }

    /**
     * Sets reversal admission field.
     */
    public function reversalAdmission(?RelationshipLinks $value): self
    {
        $this->instance->setReversalAdmission($value);
        return $this;
    }

    /**
     * Initializes a new relationships 21 object.
     */
    public function build(): Relationships21
    {
        return CoreHelper::clone($this->instance);
    }
}
