<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\RelationshipsPayment;

/**
 * Builder for model RelationshipsPayment
 *
 * @see RelationshipsPayment
 */
class RelationshipsPaymentBuilder
{
    /**
     * @var RelationshipsPayment
     */
    private $instance;

    private function __construct(RelationshipsPayment $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new relationships payment Builder object.
     */
    public static function init(): self
    {
        return new self(new RelationshipsPayment());
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new relationships payment object.
     */
    public function build(): RelationshipsPayment
    {
        return CoreHelper::clone($this->instance);
    }
}
