<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\RelationshipReturnSubmissionTasks;

/**
 * Builder for model RelationshipReturnSubmissionTasks
 *
 * @see RelationshipReturnSubmissionTasks
 */
class RelationshipReturnSubmissionTasksBuilder
{
    /**
     * @var RelationshipReturnSubmissionTasks
     */
    private $instance;

    private function __construct(RelationshipReturnSubmissionTasks $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new relationship return submission tasks Builder object.
     */
    public static function init(): self
    {
        return new self(new RelationshipReturnSubmissionTasks());
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new relationship return submission tasks object.
     */
    public function build(): RelationshipReturnSubmissionTasks
    {
        return CoreHelper::clone($this->instance);
    }
}
