<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\RelationshipQueryResponseAdmission;

/**
 * Builder for model RelationshipQueryResponseAdmission
 *
 * @see RelationshipQueryResponseAdmission
 */
class RelationshipQueryResponseAdmissionBuilder
{
    /**
     * @var RelationshipQueryResponseAdmission
     */
    private $instance;

    private function __construct(RelationshipQueryResponseAdmission $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new relationship query response admission Builder object.
     */
    public static function init(): self
    {
        return new self(new RelationshipQueryResponseAdmission());
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new relationship query response admission object.
     */
    public function build(): RelationshipQueryResponseAdmission
    {
        return CoreHelper::clone($this->instance);
    }
}
