<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\RelationshipsPaymentRecallSubmission;

/**
 * Builder for model RelationshipsPaymentRecallSubmission
 *
 * @see RelationshipsPaymentRecallSubmission
 */
class RelationshipsPaymentRecallSubmissionBuilder
{
    /**
     * @var RelationshipsPaymentRecallSubmission
     */
    private $instance;

    private function __construct(RelationshipsPaymentRecallSubmission $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new relationships payment recall submission Builder object.
     */
    public static function init(): self
    {
        return new self(new RelationshipsPaymentRecallSubmission());
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new relationships payment recall submission object.
     */
    public function build(): RelationshipsPaymentRecallSubmission
    {
        return CoreHelper::clone($this->instance);
    }
}
