<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\ReportRequestSubmissionAttributes;

/**
 * Builder for model ReportRequestSubmissionAttributes
 *
 * @see ReportRequestSubmissionAttributes
 */
class ReportRequestSubmissionAttributesBuilder
{
    /**
     * @var ReportRequestSubmissionAttributes
     */
    private $instance;

    private function __construct(ReportRequestSubmissionAttributes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new report request submission attributes Builder object.
     */
    public static function init(string $status): self
    {
        return new self(new ReportRequestSubmissionAttributes($status));
    }

    /**
     * Sets scheme status code field.
     */
    public function schemeStatusCode(?string $value): self
    {
        $this->instance->setSchemeStatusCode($value);
        return $this;
    }

    /**
     * Sets status reason field.
     */
    public function statusReason(?string $value): self
    {
        $this->instance->setStatusReason($value);
        return $this;
    }

    /**
     * Initializes a new report request submission attributes object.
     */
    public function build(): ReportRequestSubmissionAttributes
    {
        return CoreHelper::clone($this->instance);
    }
}
