<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\ReportAdmission;
use Form3PublicAPILib\Models\ReportAdmissionAttributes;
use Form3PublicAPILib\Models\ReportAdmissionRelationships;

/**
 * Builder for model ReportAdmission
 *
 * @see ReportAdmission
 */
class ReportAdmissionBuilder
{
    /**
     * @var ReportAdmission
     */
    private $instance;

    private function __construct(ReportAdmission $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new report admission Builder object.
     */
    public static function init(string $id, string $organisationId): self
    {
        return new self(new ReportAdmission($id, $organisationId));
    }

    /**
     * Sets attributes field.
     */
    public function attributes(?ReportAdmissionAttributes $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Sets created on field.
     */
    public function createdOn(?\DateTime $value): self
    {
        $this->instance->setCreatedOn($value);
        return $this;
    }

    /**
     * Sets modified on field.
     */
    public function modifiedOn(?\DateTime $value): self
    {
        $this->instance->setModifiedOn($value);
        return $this;
    }

    /**
     * Sets relationships field.
     */
    public function relationships(?ReportAdmissionRelationships $value): self
    {
        $this->instance->setRelationships($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets version field.
     */
    public function version(?int $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new report admission object.
     */
    public function build(): ReportAdmission
    {
        return CoreHelper::clone($this->instance);
    }
}
