<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\NewReportRequest;
use Form3PublicAPILib\Models\ReportRequestCreation;

/**
 * Builder for model ReportRequestCreation
 *
 * @see ReportRequestCreation
 */
class ReportRequestCreationBuilder
{
    /**
     * @var ReportRequestCreation
     */
    private $instance;

    private function __construct(ReportRequestCreation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new report request creation Builder object.
     */
    public static function init(NewReportRequest $data): self
    {
        return new self(new ReportRequestCreation($data));
    }

    /**
     * Initializes a new report request creation object.
     */
    public function build(): ReportRequestCreation
    {
        return CoreHelper::clone($this->instance);
    }
}
