<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\ReversalCreationResponse;
use Form3PublicAPILib\Models\ReversalPayment;

/**
 * Builder for model ReversalCreationResponse
 *
 * @see ReversalCreationResponse
 */
class ReversalCreationResponseBuilder
{
    /**
     * @var ReversalCreationResponse
     */
    private $instance;

    private function __construct(ReversalCreationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new reversal creation response Builder object.
     */
    public static function init(): self
    {
        return new self(new ReversalCreationResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?ReversalPayment $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new reversal creation response object.
     */
    public function build(): ReversalCreationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
