<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\ReversalAmount;

/**
 * Builder for model ReversalAmount
 *
 * @see ReversalAmount
 */
class ReversalAmountBuilder
{
    /**
     * @var ReversalAmount
     */
    private $instance;

    private function __construct(ReversalAmount $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new reversal amount Builder object.
     */
    public static function init(): self
    {
        return new self(new ReversalAmount());
    }

    /**
     * Sets amount field.
     */
    public function amount(?string $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets currency field.
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Initializes a new reversal amount object.
     */
    public function build(): ReversalAmount
    {
        return CoreHelper::clone($this->instance);
    }
}
