<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\SchemeFileSubmission;
use Form3PublicAPILib\Models\SchemeFileSubmissionCreation;

/**
 * Builder for model SchemeFileSubmissionCreation
 *
 * @see SchemeFileSubmissionCreation
 */
class SchemeFileSubmissionCreationBuilder
{
    /**
     * @var SchemeFileSubmissionCreation
     */
    private $instance;

    private function __construct(SchemeFileSubmissionCreation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new scheme file submission creation Builder object.
     */
    public static function init(SchemeFileSubmission $data): self
    {
        return new self(new SchemeFileSubmissionCreation($data));
    }

    /**
     * Initializes a new scheme file submission creation object.
     */
    public function build(): SchemeFileSubmissionCreation
    {
        return CoreHelper::clone($this->instance);
    }
}
