<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\SchemeMessage;
use Form3PublicAPILib\Models\SchemeMessageAttributes;
use Form3PublicAPILib\Models\SchemeMessageRelationships;

/**
 * Builder for model SchemeMessage
 *
 * @see SchemeMessage
 */
class SchemeMessageBuilder
{
    /**
     * @var SchemeMessage
     */
    private $instance;

    private function __construct(SchemeMessage $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new scheme message Builder object.
     */
    public static function init(SchemeMessageAttributes $attributes, string $id, string $organisationId): self
    {
        return new self(new SchemeMessage($attributes, $id, $organisationId));
    }

    /**
     * Sets relationships field.
     */
    public function relationships(?SchemeMessageRelationships $value): self
    {
        $this->instance->setRelationships($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets version field.
     */
    public function version(?int $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new scheme message object.
     */
    public function build(): SchemeMessage
    {
        return CoreHelper::clone($this->instance);
    }
}
