<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\SortCode;
use Form3PublicAPILib\Models\SortCodeDetailsResponse;

/**
 * Builder for model SortCodeDetailsResponse
 *
 * @see SortCodeDetailsResponse
 */
class SortCodeDetailsResponseBuilder
{
    /**
     * @var SortCodeDetailsResponse
     */
    private $instance;

    private function __construct(SortCodeDetailsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new sort code details response Builder object.
     */
    public static function init(): self
    {
        return new self(new SortCodeDetailsResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?SortCode $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new sort code details response object.
     */
    public function build(): SortCodeDetailsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
