<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\TransactionFileAdmissionRelationships;
use Form3PublicAPILib\Models\TransactionFiles;

/**
 * Builder for model TransactionFileAdmissionRelationships
 *
 * @see TransactionFileAdmissionRelationships
 */
class TransactionFileAdmissionRelationshipsBuilder
{
    /**
     * @var TransactionFileAdmissionRelationships
     */
    private $instance;

    private function __construct(TransactionFileAdmissionRelationships $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new transaction file admission relationships Builder object.
     */
    public static function init(): self
    {
        return new self(new TransactionFileAdmissionRelationships());
    }

    /**
     * Sets transaction files field.
     */
    public function transactionFiles(?TransactionFiles $value): self
    {
        $this->instance->setTransactionFiles($value);
        return $this;
    }

    /**
     * Initializes a new transaction file admission relationships object.
     */
    public function build(): TransactionFileAdmissionRelationships
    {
        return CoreHelper::clone($this->instance);
    }
}
