<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\TransactionFileSubmission;
use Form3PublicAPILib\Models\TransactionFileSubmissionCreation;

/**
 * Builder for model TransactionFileSubmissionCreation
 *
 * @see TransactionFileSubmissionCreation
 */
class TransactionFileSubmissionCreationBuilder
{
    /**
     * @var TransactionFileSubmissionCreation
     */
    private $instance;

    private function __construct(TransactionFileSubmissionCreation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new transaction file submission creation Builder object.
     */
    public static function init(TransactionFileSubmission $data): self
    {
        return new self(new TransactionFileSubmissionCreation($data));
    }

    /**
     * Initializes a new transaction file submission creation object.
     */
    public function build(): TransactionFileSubmissionCreation
    {
        return CoreHelper::clone($this->instance);
    }
}
