<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\NewTransactionFile;
use Form3PublicAPILib\Models\TransactionFileCreation;

/**
 * Builder for model TransactionFileCreation
 *
 * @see TransactionFileCreation
 */
class TransactionFileCreationBuilder
{
    /**
     * @var TransactionFileCreation
     */
    private $instance;

    private function __construct(TransactionFileCreation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new transaction file creation Builder object.
     */
    public static function init(NewTransactionFile $data): self
    {
        return new self(new TransactionFileCreation($data));
    }

    /**
     * Initializes a new transaction file creation object.
     */
    public function build(): TransactionFileCreation
    {
        return CoreHelper::clone($this->instance);
    }
}
