<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\TransactionFile;
use Form3PublicAPILib\Models\TransactionFileLinks;
use Form3PublicAPILib\Models\TransactionFileResponse;

/**
 * Builder for model TransactionFileResponse
 *
 * @see TransactionFileResponse
 */
class TransactionFileResponseBuilder
{
    /**
     * @var TransactionFileResponse
     */
    private $instance;

    private function __construct(TransactionFileResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new transaction file response Builder object.
     */
    public static function init(): self
    {
        return new self(new TransactionFileResponse());
    }

    /**
     * Sets data field.
     */
    public function data(?TransactionFile $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets links field.
     */
    public function links(?TransactionFileLinks $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new transaction file response object.
     */
    public function build(): TransactionFileResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
