<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\TransactionFiles;

/**
 * Builder for model TransactionFiles
 *
 * @see TransactionFiles
 */
class TransactionFilesBuilder
{
    /**
     * @var TransactionFiles
     */
    private $instance;

    private function __construct(TransactionFiles $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new transaction files Builder object.
     */
    public static function init(): self
    {
        return new self(new TransactionFiles());
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new transaction files object.
     */
    public function build(): TransactionFiles
    {
        return CoreHelper::clone($this->instance);
    }
}
