<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Attributes42;
use Form3PublicAPILib\Models\TransactionFile;
use Form3PublicAPILib\Models\TransactionFileRelationships;

/**
 * Builder for model TransactionFile
 *
 * @see TransactionFile
 */
class TransactionFileBuilder
{
    /**
     * @var TransactionFile
     */
    private $instance;

    private function __construct(TransactionFile $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new transaction file Builder object.
     */
    public static function init(Attributes42 $attributes, string $id, string $organisationId): self
    {
        return new self(new TransactionFile($attributes, $id, $organisationId));
    }

    /**
     * Sets created on field.
     */
    public function createdOn(?\DateTime $value): self
    {
        $this->instance->setCreatedOn($value);
        return $this;
    }

    /**
     * Sets modified on field.
     */
    public function modifiedOn(?\DateTime $value): self
    {
        $this->instance->setModifiedOn($value);
        return $this;
    }

    /**
     * Sets relationships field.
     */
    public function relationships(?TransactionFileRelationships $value): self
    {
        $this->instance->setRelationships($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets version field.
     */
    public function version(?int $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new transaction file object.
     */
    public function build(): TransactionFile
    {
        return CoreHelper::clone($this->instance);
    }
}
