<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\UserDefinedData;

/**
 * Builder for model UserDefinedData
 *
 * @see UserDefinedData
 */
class UserDefinedDataBuilder
{
    /**
     * @var UserDefinedData
     */
    private $instance;

    private function __construct(UserDefinedData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new user defined data Builder object.
     */
    public static function init(string $key, string $value): self
    {
        return new self(new UserDefinedData($key, $value));
    }

    /**
     * Initializes a new user defined data object.
     */
    public function build(): UserDefinedData
    {
        return CoreHelper::clone($this->instance);
    }
}
