<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\User;
use Form3PublicAPILib\Models\UserCreationResponse;

/**
 * Builder for model UserCreationResponse
 *
 * @see UserCreationResponse
 */
class UserCreationResponseBuilder
{
    /**
     * @var UserCreationResponse
     */
    private $instance;

    private function __construct(UserCreationResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new user creation response Builder object.
     */
    public static function init(User $data): self
    {
        return new self(new UserCreationResponse($data));
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new user creation response object.
     */
    public function build(): UserCreationResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
