<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use Form3PublicAPILib\Models\Links;
use Form3PublicAPILib\Models\UserRoleListResponse;

/**
 * Builder for model UserRoleListResponse
 *
 * @see UserRoleListResponse
 */
class UserRoleListResponseBuilder
{
    /**
     * @var UserRoleListResponse
     */
    private $instance;

    private function __construct(UserRoleListResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new user role list response Builder object.
     */
    public static function init(array $data): self
    {
        return new self(new UserRoleListResponse($data));
    }

    /**
     * Sets links field.
     */
    public function links(?Links $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Initializes a new user role list response object.
     */
    public function build(): UserRoleListResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
