<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * All accepted payments will receive the matching qualifier code
 */
class AcceptanceQualifierEnum
{
    public const SOME_OTHER_TIME = 'some_other_time';

    public const SAME_DAY = 'same_day';

    public const NEXT_CALENDAR_DAY = 'next_calendar_day';

    public const NEXT_WORKING_DAY = 'next_working_day';

    public const AFTER_NEXT_WORKING_DAY = 'after_next_working_day';

    public const NONE = 'none';

    private const _ALL_VALUES = [
        self::SOME_OTHER_TIME,
        self::SAME_DAY,
        self::NEXT_CALENDAR_DAY,
        self::NEXT_WORKING_DAY,
        self::AFTER_NEXT_WORKING_DAY,
        self::NONE
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for AcceptanceQualifierEnum.");
    }
}
