<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

class AccountIdentificationAttributes implements \JsonSerializable
{
    /**
     * @var string
     */
    private $secondaryIdentification;

    /**
     * @param string $secondaryIdentification
     */
    public function __construct(string $secondaryIdentification)
    {
        $this->secondaryIdentification = $secondaryIdentification;
    }

    /**
     * Returns Secondary Identification.
     * Used to validate where expecting an exact match against payment's reference information.
     */
    public function getSecondaryIdentification(): string
    {
        return $this->secondaryIdentification;
    }

    /**
     * Sets Secondary Identification.
     * Used to validate where expecting an exact match against payment's reference information.
     *
     * @required
     * @maps secondary_identification
     */
    public function setSecondaryIdentification(string $secondaryIdentification): void
    {
        $this->secondaryIdentification = $secondaryIdentification;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['secondary_identification'] = $this->secondaryIdentification;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
