<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

/**
 * Debtor/Beneficiary agents bank information.
 */
class AccountWith implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $bankId;

    /**
     * @var string|null
     */
    private $bankIdCode;

    /**
     * @var string|null
     */
    private $bankName;

    /**
     * Returns Bank Id.
     * Identification of a member of a clearing system.
     */
    public function getBankId(): ?string
    {
        return $this->bankId;
    }

    /**
     * Sets Bank Id.
     * Identification of a member of a clearing system.
     *
     * @maps bank_id
     */
    public function setBankId(?string $bankId): void
    {
        $this->bankId = $bankId;
    }

    /**
     * Returns Bank Id Code.
     * Identification of a clearing system, in a coded form as published in an external list.
     */
    public function getBankIdCode(): ?string
    {
        return $this->bankIdCode;
    }

    /**
     * Sets Bank Id Code.
     * Identification of a clearing system, in a coded form as published in an external list.
     *
     * @maps bank_id_code
     */
    public function setBankIdCode(?string $bankIdCode): void
    {
        $this->bankIdCode = $bankIdCode;
    }

    /**
     * Returns Bank Name.
     * Name by which an agent is known and which is usually used to identify that agent.
     */
    public function getBankName(): ?string
    {
        return $this->bankName;
    }

    /**
     * Sets Bank Name.
     * Name by which an agent is known and which is usually used to identify that agent.
     *
     * @maps bank_name
     */
    public function setBankName(?string $bankName): void
    {
        $this->bankName = $bankName;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->bankId)) {
            $json['bank_id']      = $this->bankId;
        }
        if (isset($this->bankIdCode)) {
            $json['bank_id_code'] = $this->bankIdCode;
        }
        if (isset($this->bankName)) {
            $json['bank_name']    = $this->bankName;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
