<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

class Attributes50 implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $auto;

    /**
     * Returns Auto.
     */
    public function getAuto(): ?bool
    {
        return $this->auto;
    }

    /**
     * Sets Auto.
     *
     * @maps auto
     */
    public function setAuto(?bool $auto): void
    {
        $this->auto = $auto;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->auto)) {
            $json['auto'] = $this->auto;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
