<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use Form3PublicAPILib\Utils\DateTimeHelper;
use stdClass;

class Attributes68 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $schemeStatusCode;

    /**
     * @var string|null
     */
    private $schemeStatusCodeDescription;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $statusReason;

    /**
     * @var \DateTime|null
     */
    private $submissionDatetime;

    /**
     * @var \DateTime|null
     */
    private $transactionStartDatetime;

    /**
     * Returns Scheme Status Code.
     * Scheme-specific status code, refer to scheme documentation
     */
    public function getSchemeStatusCode(): ?string
    {
        return $this->schemeStatusCode;
    }

    /**
     * Sets Scheme Status Code.
     * Scheme-specific status code, refer to scheme documentation
     *
     * @maps scheme_status_code
     */
    public function setSchemeStatusCode(?string $schemeStatusCode): void
    {
        $this->schemeStatusCode = $schemeStatusCode;
    }

    /**
     * Returns Scheme Status Code Description.
     * Description of `scheme_status_code`
     */
    public function getSchemeStatusCodeDescription(): ?string
    {
        return $this->schemeStatusCodeDescription;
    }

    /**
     * Sets Scheme Status Code Description.
     * Description of `scheme_status_code`
     *
     * @maps scheme_status_code_description
     */
    public function setSchemeStatusCodeDescription(?string $schemeStatusCodeDescription): void
    {
        $this->schemeStatusCodeDescription = $schemeStatusCodeDescription;
    }

    /**
     * Returns Status.
     * [Status of the reversal submission](http://draft-api-docs.form3.tech/api.html#enumerations-reversal-
     * submission-status)
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * [Status of the reversal submission](http://draft-api-docs.form3.tech/api.html#enumerations-reversal-
     * submission-status)
     *
     * @maps status
     * @factory \Form3PublicAPILib\Models\ReversalSubmissionStatusEnum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Status Reason.
     * Description of the reversal submission status
     */
    public function getStatusReason(): ?string
    {
        return $this->statusReason;
    }

    /**
     * Sets Status Reason.
     * Description of the reversal submission status
     *
     * @maps status_reason
     */
    public function setStatusReason(?string $statusReason): void
    {
        $this->statusReason = $statusReason;
    }

    /**
     * Returns Submission Datetime.
     * Date of the reversal submission
     */
    public function getSubmissionDatetime(): ?\DateTime
    {
        return $this->submissionDatetime;
    }

    /**
     * Sets Submission Datetime.
     * Date of the reversal submission
     *
     * @maps submission_datetime
     * @factory \Form3PublicAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setSubmissionDatetime(?\DateTime $submissionDatetime): void
    {
        $this->submissionDatetime = $submissionDatetime;
    }

    /**
     * Returns Transaction Start Datetime.
     * Time the request was received by Form3. Used to compute the total transaction time of a payment.
     */
    public function getTransactionStartDatetime(): ?\DateTime
    {
        return $this->transactionStartDatetime;
    }

    /**
     * Sets Transaction Start Datetime.
     * Time the request was received by Form3. Used to compute the total transaction time of a payment.
     *
     * @maps transaction_start_datetime
     * @factory \Form3PublicAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTransactionStartDatetime(?\DateTime $transactionStartDatetime): void
    {
        $this->transactionStartDatetime = $transactionStartDatetime;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->schemeStatusCode)) {
            $json['scheme_status_code']             = $this->schemeStatusCode;
        }
        if (isset($this->schemeStatusCodeDescription)) {
            $json['scheme_status_code_description'] = $this->schemeStatusCodeDescription;
        }
        if (isset($this->status)) {
            $json['status']                         = ReversalSubmissionStatusEnum::checkValue($this->status);
        }
        if (isset($this->statusReason)) {
            $json['status_reason']                  = $this->statusReason;
        }
        if (isset($this->submissionDatetime)) {
            $json['submission_datetime']            = DateTimeHelper::toRfc3339DateTime($this->submissionDatetime);
        }
        if (isset($this->transactionStartDatetime)) {
            $json['transaction_start_datetime']     =
                DateTimeHelper::toRfc3339DateTime(
                    $this->transactionStartDatetime
                );
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
