<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use Form3PublicAPILib\Utils\DateTimeHelper;
use stdClass;

class Attributes26 implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $admissionDatetime;

    /**
     * @var string|null
     */
    private $sourceGateway;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $statusReason;

    /**
     * Returns Admission Datetime.
     */
    public function getAdmissionDatetime(): ?\DateTime
    {
        return $this->admissionDatetime;
    }

    /**
     * Sets Admission Datetime.
     *
     * @maps admission_datetime
     * @factory \Form3PublicAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setAdmissionDatetime(?\DateTime $admissionDatetime): void
    {
        $this->admissionDatetime = $admissionDatetime;
    }

    /**
     * Returns Source Gateway.
     */
    public function getSourceGateway(): ?string
    {
        return $this->sourceGateway;
    }

    /**
     * Sets Source Gateway.
     *
     * @maps source_gateway
     */
    public function setSourceGateway(?string $sourceGateway): void
    {
        $this->sourceGateway = $sourceGateway;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     * @factory \Form3PublicAPILib\Models\DirectDebitDecisionAdmissionStatusEnum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Status Reason.
     */
    public function getStatusReason(): ?string
    {
        return $this->statusReason;
    }

    /**
     * Sets Status Reason.
     *
     * @maps status_reason
     * @factory \Form3PublicAPILib\Models\DirectDebitDecisionAdmissionStatusReasonEnum::checkValue
     */
    public function setStatusReason(?string $statusReason): void
    {
        $this->statusReason = $statusReason;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->admissionDatetime)) {
            $json['admission_datetime'] = DateTimeHelper::toRfc3339DateTime($this->admissionDatetime);
        }
        if (isset($this->sourceGateway)) {
            $json['source_gateway']     = $this->sourceGateway;
        }
        if (isset($this->status)) {
            $json['status']             = DirectDebitDecisionAdmissionStatusEnum::checkValue($this->status);
        }
        if (isset($this->statusReason)) {
            $json['status_reason']      = DirectDebitDecisionAdmissionStatusReasonEnum::checkValue($this->statusReason);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
