<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class FilterNotRelationships1Enum
{
    public const PAYMENT_SUBMISSIONS = 'payment_submissions';

    public const PAYMENT_ADMISSIONS = 'payment_admissions';

    public const REVERSALS = 'reversals';

    public const RECALLS = 'recalls';

    public const RETURNS = 'returns';

    public const PAYMENT_ADVICES = 'payment_advices';

    private const _ALL_VALUES = [
        self::PAYMENT_SUBMISSIONS,
        self::PAYMENT_ADMISSIONS,
        self::REVERSALS,
        self::RECALLS,
        self::RETURNS,
        self::PAYMENT_ADVICES
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for FilterNotRelationships1Enum.");
    }
}
