<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class MandateAdmissionStatusReasonEnum
{
    public const ACCEPTED = 'accepted';

    public const INVALID_BENEFICIARY_DETAILS = 'invalid_beneficiary_details';

    public const BANKID_NOT_PROVISIONED = 'bankid_not_provisioned';

    public const UNKNOWN_ACCOUNTNUMBER = 'unknown_accountnumber';

    public const MANDATE_CANCELLED = 'mandate_cancelled';

    public const MANDATE_EXPIRED = 'mandate_expired';

    public const MANDATE_FAILED = 'mandate_failed';

    public const UNKNOWN_INSTRUCTION = 'unknown_instruction';

    public const PAYER_REFERENCE_NOT_UNIQUE = 'payer_reference_not_unique';

    public const INVALID_REFERENCE = 'invalid_reference';

    public const NOT_ELIGIBLE_FOR_REINSTATEMENT_BY_ORIGINATOR = 'not_eligible_for_reinstatement_by_originator';

    private const _ALL_VALUES = [
        self::ACCEPTED,
        self::INVALID_BENEFICIARY_DETAILS,
        self::BANKID_NOT_PROVISIONED,
        self::UNKNOWN_ACCOUNTNUMBER,
        self::MANDATE_CANCELLED,
        self::MANDATE_EXPIRED,
        self::MANDATE_FAILED,
        self::UNKNOWN_INSTRUCTION,
        self::PAYER_REFERENCE_NOT_UNIQUE,
        self::INVALID_REFERENCE,
        self::NOT_ELIGIBLE_FOR_REINSTATEMENT_BY_ORIGINATOR
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for MandateAdmissionStatusReasonEnum.");
    }
}
