<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

class RecallReversalAdmissionAttributes implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $schemeStatusCode;

    /**
     * @var string|null
     */
    private $sourceGateway;

    /**
     * Returns Scheme Status Code.
     * Scheme-specific status code
     */
    public function getSchemeStatusCode(): ?string
    {
        return $this->schemeStatusCode;
    }

    /**
     * Sets Scheme Status Code.
     * Scheme-specific status code
     *
     * @maps scheme_status_code
     */
    public function setSchemeStatusCode(?string $schemeStatusCode): void
    {
        $this->schemeStatusCode = $schemeStatusCode;
    }

    /**
     * Returns Source Gateway.
     */
    public function getSourceGateway(): ?string
    {
        return $this->sourceGateway;
    }

    /**
     * Sets Source Gateway.
     *
     * @maps source_gateway
     */
    public function setSourceGateway(?string $sourceGateway): void
    {
        $this->sourceGateway = $sourceGateway;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->schemeStatusCode)) {
            $json['scheme_status_code'] = $this->schemeStatusCode;
        }
        if (isset($this->sourceGateway)) {
            $json['source_gateway']     = $this->sourceGateway;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
