<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

class Relationships8 implements \JsonSerializable
{
    /**
     * @var DirectDebit1|null
     */
    private $directDebit;

    /**
     * @var DirectDebitRecall2|null
     */
    private $directDebitRecall;

    /**
     * Returns Direct Debit.
     */
    public function getDirectDebit(): ?DirectDebit1
    {
        return $this->directDebit;
    }

    /**
     * Sets Direct Debit.
     *
     * @maps direct_debit
     */
    public function setDirectDebit(?DirectDebit1 $directDebit): void
    {
        $this->directDebit = $directDebit;
    }

    /**
     * Returns Direct Debit Recall.
     */
    public function getDirectDebitRecall(): ?DirectDebitRecall2
    {
        return $this->directDebitRecall;
    }

    /**
     * Sets Direct Debit Recall.
     *
     * @maps direct_debit_recall
     */
    public function setDirectDebitRecall(?DirectDebitRecall2 $directDebitRecall): void
    {
        $this->directDebitRecall = $directDebitRecall;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->directDebit)) {
            $json['direct_debit']        = $this->directDebit;
        }
        if (isset($this->directDebitRecall)) {
            $json['direct_debit_recall'] = $this->directDebitRecall;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
