<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

class Relationships17 implements \JsonSerializable
{
    /**
     * @var Mandate2|null
     */
    private $mandate;

    /**
     * @var MandateReturnSubmission2|null
     */
    private $mandateReturnSubmission;

    /**
     * Returns Mandate.
     */
    public function getMandate(): ?Mandate2
    {
        return $this->mandate;
    }

    /**
     * Sets Mandate.
     *
     * @maps mandate
     */
    public function setMandate(?Mandate2 $mandate): void
    {
        $this->mandate = $mandate;
    }

    /**
     * Returns Mandate Return Submission.
     */
    public function getMandateReturnSubmission(): ?MandateReturnSubmission2
    {
        return $this->mandateReturnSubmission;
    }

    /**
     * Sets Mandate Return Submission.
     *
     * @maps mandate_return_submission
     */
    public function setMandateReturnSubmission(?MandateReturnSubmission2 $mandateReturnSubmission): void
    {
        $this->mandateReturnSubmission = $mandateReturnSubmission;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->mandate)) {
            $json['mandate']                   = $this->mandate;
        }
        if (isset($this->mandateReturnSubmission)) {
            $json['mandate_return_submission'] = $this->mandateReturnSubmission;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
