<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

class Relationships10 implements \JsonSerializable
{
    /**
     * @var DirectDebit1|null
     */
    private $directDebit;

    /**
     * @var DirectDebitReturnAdmission2|null
     */
    private $directDebitReturnAdmission;

    /**
     * @var DirectDebitReturnReversal2|null
     */
    private $directDebitReturnReversal;

    /**
     * @var DirectDebitReturnSubmission2|null
     */
    private $directDebitReturnSubmission;

    /**
     * Returns Direct Debit.
     */
    public function getDirectDebit(): ?DirectDebit1
    {
        return $this->directDebit;
    }

    /**
     * Sets Direct Debit.
     *
     * @maps direct_debit
     */
    public function setDirectDebit(?DirectDebit1 $directDebit): void
    {
        $this->directDebit = $directDebit;
    }

    /**
     * Returns Direct Debit Return Admission.
     */
    public function getDirectDebitReturnAdmission(): ?DirectDebitReturnAdmission2
    {
        return $this->directDebitReturnAdmission;
    }

    /**
     * Sets Direct Debit Return Admission.
     *
     * @maps direct_debit_return_admission
     */
    public function setDirectDebitReturnAdmission(?DirectDebitReturnAdmission2 $directDebitReturnAdmission): void
    {
        $this->directDebitReturnAdmission = $directDebitReturnAdmission;
    }

    /**
     * Returns Direct Debit Return Reversal.
     */
    public function getDirectDebitReturnReversal(): ?DirectDebitReturnReversal2
    {
        return $this->directDebitReturnReversal;
    }

    /**
     * Sets Direct Debit Return Reversal.
     *
     * @maps direct_debit_return_reversal
     */
    public function setDirectDebitReturnReversal(?DirectDebitReturnReversal2 $directDebitReturnReversal): void
    {
        $this->directDebitReturnReversal = $directDebitReturnReversal;
    }

    /**
     * Returns Direct Debit Return Submission.
     */
    public function getDirectDebitReturnSubmission(): ?DirectDebitReturnSubmission2
    {
        return $this->directDebitReturnSubmission;
    }

    /**
     * Sets Direct Debit Return Submission.
     *
     * @maps direct_debit_return_submission
     */
    public function setDirectDebitReturnSubmission(?DirectDebitReturnSubmission2 $directDebitReturnSubmission): void
    {
        $this->directDebitReturnSubmission = $directDebitReturnSubmission;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->directDebit)) {
            $json['direct_debit']                   = $this->directDebit;
        }
        if (isset($this->directDebitReturnAdmission)) {
            $json['direct_debit_return_admission']  = $this->directDebitReturnAdmission;
        }
        if (isset($this->directDebitReturnReversal)) {
            $json['direct_debit_return_reversal']   = $this->directDebitReturnReversal;
        }
        if (isset($this->directDebitReturnSubmission)) {
            $json['direct_debit_return_submission'] = $this->directDebitReturnSubmission;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
