<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

class ReportUser implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $userId;

    /**
     * @var string|null
     */
    private $userIdCode;

    /**
     * Returns User Id.
     * Identifies a user or organization
     */
    public function getUserId(): ?string
    {
        return $this->userId;
    }

    /**
     * Sets User Id.
     * Identifies a user or organization
     *
     * @maps user_id
     */
    public function setUserId(?string $userId): void
    {
        $this->userId = $userId;
    }

    /**
     * Returns User Id Code.
     * Type of identifier for the user or organization
     */
    public function getUserIdCode(): ?string
    {
        return $this->userIdCode;
    }

    /**
     * Sets User Id Code.
     * Type of identifier for the user or organization
     *
     * @maps user_id_code
     */
    public function setUserIdCode(?string $userIdCode): void
    {
        $this->userIdCode = $userIdCode;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->userId)) {
            $json['user_id']      = $this->userId;
        }
        if (isset($this->userIdCode)) {
            $json['user_id_code'] = $this->userIdCode;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
