<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

class ReportRequestLinks implements \JsonSerializable
{
    /**
     * @var ReportRequestLink
     */
    private $self;

    /**
     * @param ReportRequestLink $self
     */
    public function __construct(ReportRequestLink $self)
    {
        $this->self = $self;
    }

    /**
     * Returns Self.
     */
    public function getSelf(): ReportRequestLink
    {
        return $this->self;
    }

    /**
     * Sets Self.
     *
     * @required
     * @maps self
     */
    public function setSelf(ReportRequestLink $self): void
    {
        $this->self = $self;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['self'] = $this->self;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
