<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

class ReturnPaymentRelationships implements \JsonSerializable
{
    /**
     * @var RelationshipPayments|null
     */
    private $payment;

    /**
     * @var ReturnAdmission2|null
     */
    private $returnAdmission;

    /**
     * @var RelationshipLinks|null
     */
    private $returnReversal;

    /**
     * @var ReturnSubmission2|null
     */
    private $returnSubmission;

    /**
     * Returns Payment.
     */
    public function getPayment(): ?RelationshipPayments
    {
        return $this->payment;
    }

    /**
     * Sets Payment.
     *
     * @maps payment
     */
    public function setPayment(?RelationshipPayments $payment): void
    {
        $this->payment = $payment;
    }

    /**
     * Returns Return Admission.
     */
    public function getReturnAdmission(): ?ReturnAdmission2
    {
        return $this->returnAdmission;
    }

    /**
     * Sets Return Admission.
     *
     * @maps return_admission
     */
    public function setReturnAdmission(?ReturnAdmission2 $returnAdmission): void
    {
        $this->returnAdmission = $returnAdmission;
    }

    /**
     * Returns Return Reversal.
     */
    public function getReturnReversal(): ?RelationshipLinks
    {
        return $this->returnReversal;
    }

    /**
     * Sets Return Reversal.
     *
     * @maps return_reversal
     */
    public function setReturnReversal(?RelationshipLinks $returnReversal): void
    {
        $this->returnReversal = $returnReversal;
    }

    /**
     * Returns Return Submission.
     */
    public function getReturnSubmission(): ?ReturnSubmission2
    {
        return $this->returnSubmission;
    }

    /**
     * Sets Return Submission.
     *
     * @maps return_submission
     */
    public function setReturnSubmission(?ReturnSubmission2 $returnSubmission): void
    {
        $this->returnSubmission = $returnSubmission;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->payment)) {
            $json['payment']           = $this->payment;
        }
        if (isset($this->returnAdmission)) {
            $json['return_admission']  = $this->returnAdmission;
        }
        if (isset($this->returnReversal)) {
            $json['return_reversal']   = $this->returnReversal;
        }
        if (isset($this->returnSubmission)) {
            $json['return_submission'] = $this->returnSubmission;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
