<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use Form3PublicAPILib\Utils\DateTimeHelper;
use stdClass;

class SigningKeysResponseData implements \JsonSerializable
{
    /**
     * @var SigningKeysAttributes
     */
    private $attributes;

    /**
     * @var \DateTime|null
     */
    private $createdOn;

    /**
     * @var string
     */
    private $id;

    /**
     * @var \DateTime|null
     */
    private $modifiedOn;

    /**
     * @var string
     */
    private $organisationId;

    /**
     * @var string
     */
    private $type;

    /**
     * @var int
     */
    private $version;

    /**
     * @param SigningKeysAttributes $attributes
     * @param string $id
     * @param string $organisationId
     * @param int $version
     */
    public function __construct(SigningKeysAttributes $attributes, string $id, string $organisationId, int $version)
    {
        $this->attributes = $attributes;
        $this->id = $id;
        $this->organisationId = $organisationId;
        $this->version = $version;
    }

    /**
     * Returns Attributes.
     */
    public function getAttributes(): SigningKeysAttributes
    {
        return $this->attributes;
    }

    /**
     * Sets Attributes.
     *
     * @required
     * @maps attributes
     */
    public function setAttributes(SigningKeysAttributes $attributes): void
    {
        $this->attributes = $attributes;
    }

    /**
     * Returns Created On.
     */
    public function getCreatedOn(): ?\DateTime
    {
        return $this->createdOn;
    }

    /**
     * Sets Created On.
     *
     * @maps created_on
     * @factory \Form3PublicAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreatedOn(?\DateTime $createdOn): void
    {
        $this->createdOn = $createdOn;
    }

    /**
     * Returns Id.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Modified On.
     */
    public function getModifiedOn(): ?\DateTime
    {
        return $this->modifiedOn;
    }

    /**
     * Sets Modified On.
     *
     * @maps modified_on
     * @factory \Form3PublicAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setModifiedOn(?\DateTime $modifiedOn): void
    {
        $this->modifiedOn = $modifiedOn;
    }

    /**
     * Returns Organisation Id.
     */
    public function getOrganisationId(): string
    {
        return $this->organisationId;
    }

    /**
     * Sets Organisation Id.
     *
     * @required
     * @maps organisation_id
     */
    public function setOrganisationId(string $organisationId): void
    {
        $this->organisationId = $organisationId;
    }

    /**
     * Returns Type.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Version.
     */
    public function getVersion(): int
    {
        return $this->version;
    }

    /**
     * Sets Version.
     *
     * @required
     * @maps version
     */
    public function setVersion(int $version): void
    {
        $this->version = $version;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['attributes']      = $this->attributes;
        if (isset($this->createdOn)) {
            $json['created_on']  = DateTimeHelper::toRfc3339DateTime($this->createdOn);
        }
        $json['id']              = $this->id;
        if (isset($this->modifiedOn)) {
            $json['modified_on'] = DateTimeHelper::toRfc3339DateTime($this->modifiedOn);
        }
        $json['organisation_id'] = $this->organisationId;
        $json['type']            = $this->type;
        $json['version']         = $this->version;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
