<?php

declare(strict_types=1);

/*
 * Form3PublicAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace Form3PublicAPILib\Models;

use stdClass;

class Swift implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $bankOperationCode;

    /**
     * @var Header|null
     */
    private $header;

    /**
     * @var string|null
     */
    private $instructionCode;

    /**
     * @var string|null
     */
    private $senderReceiverInformation;

    /**
     * @var string|null
     */
    private $timeIndication;

    /**
     * Returns Bank Operation Code.
     * SWIFT service level
     */
    public function getBankOperationCode(): ?string
    {
        return $this->bankOperationCode;
    }

    /**
     * Sets Bank Operation Code.
     * SWIFT service level
     *
     * @maps bank_operation_code
     */
    public function setBankOperationCode(?string $bankOperationCode): void
    {
        $this->bankOperationCode = $bankOperationCode;
    }

    /**
     * Returns Header.
     */
    public function getHeader(): ?Header
    {
        return $this->header;
    }

    /**
     * Sets Header.
     *
     * @maps header
     */
    public function setHeader(?Header $header): void
    {
        $this->header = $header;
    }

    /**
     * Returns Instruction Code.
     * A SWIFT instruction code
     */
    public function getInstructionCode(): ?string
    {
        return $this->instructionCode;
    }

    /**
     * Sets Instruction Code.
     * A SWIFT instruction code
     *
     * @maps instruction_code
     */
    public function setInstructionCode(?string $instructionCode): void
    {
        $this->instructionCode = $instructionCode;
    }

    /**
     * Returns Sender Receiver Information.
     * This field specifies additional information for the Receiver or other party specified.
     */
    public function getSenderReceiverInformation(): ?string
    {
        return $this->senderReceiverInformation;
    }

    /**
     * Sets Sender Receiver Information.
     * This field specifies additional information for the Receiver or other party specified.
     *
     * @maps sender_receiver_information
     */
    public function setSenderReceiverInformation(?string $senderReceiverInformation): void
    {
        $this->senderReceiverInformation = $senderReceiverInformation;
    }

    /**
     * Returns Time Indication.
     * This repetitive field specifies one or several time indication(s) related to the processing of the
     * payment instruction.
     */
    public function getTimeIndication(): ?string
    {
        return $this->timeIndication;
    }

    /**
     * Sets Time Indication.
     * This repetitive field specifies one or several time indication(s) related to the processing of the
     * payment instruction.
     *
     * @maps time_indication
     */
    public function setTimeIndication(?string $timeIndication): void
    {
        $this->timeIndication = $timeIndication;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->bankOperationCode)) {
            $json['bank_operation_code']         = $this->bankOperationCode;
        }
        if (isset($this->header)) {
            $json['header']                      = $this->header;
        }
        if (isset($this->instructionCode)) {
            $json['instruction_code']            = $this->instructionCode;
        }
        if (isset($this->senderReceiverInformation)) {
            $json['sender_receiver_information'] = $this->senderReceiverInformation;
        }
        if (isset($this->timeIndication)) {
            $json['time_indication']             = $this->timeIndication;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
